//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XamarinAppTemplate.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XamarinAppTemplate.Resx.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العربية.
        /// </summary>
        public static string Arabic {
            get {
                return ResourceManager.GetString("Arabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل أنت متأكد ؟.
        /// </summary>
        public static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الغاء.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العاصمة.
        /// </summary>
        public static string Capital {
            get {
                return ResourceManager.GetString("Capital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغيير اللغة سيؤدي الى اعادة التطبيق من البداية.
        /// </summary>
        public static string ChangeLangugeMsg {
            get {
                return ResourceManager.GetString("ChangeLangugeMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اغلاق.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرمز.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدخلات.
        /// </summary>
        public static string Controls {
            get {
                return ResourceManager.GetString("Controls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدول.
        /// </summary>
        public static string Countries {
            get {
                return ResourceManager.GetString("Countries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هوية.
        /// </summary>
        public static string Demo_Brand {
            get {
                return ResourceManager.GetString("Demo_Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأزرار.
        /// </summary>
        public static string Demo_Buttons {
            get {
                return ResourceManager.GetString("Demo_Buttons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خانات الاختيار.
        /// </summary>
        public static string Demo_Checkboxes {
            get {
                return ResourceManager.GetString("Demo_Checkboxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الاختيار.
        /// </summary>
        public static string Demo_Checked {
            get {
                return ResourceManager.GetString("Demo_Checked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوان.
        /// </summary>
        public static string Demo_Colors {
            get {
                return ResourceManager.GetString("Demo_Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطر.
        /// </summary>
        public static string Demo_Danger {
            get {
                return ResourceManager.GetString("Demo_Danger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اظهار مربع نص الخطأ.
        /// </summary>
        public static string Demo_ErrorModal {
            get {
                return ResourceManager.GetString("Demo_ErrorModal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نماذج الادخال.
        /// </summary>
        public static string Demo_Forms {
            get {
                return ResourceManager.GetString("Demo_Forms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نموذج ادخال مع التحقق.
        /// </summary>
        public static string Demo_FormValidation {
            get {
                return ResourceManager.GetString("Demo_FormValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خط كبير.
        /// </summary>
        public static string Demo_LargeFont {
            get {
                return ResourceManager.GetString("Demo_LargeFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مربع الانتظار.
        /// </summary>
        public static string Demo_Loading {
            get {
                return ResourceManager.GetString("Demo_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خط متوسط.
        /// </summary>
        public static string Demo_MediumFont {
            get {
                return ResourceManager.GetString("Demo_MediumFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خط مجهري.
        /// </summary>
        public static string Demo_MicroFont {
            get {
                return ResourceManager.GetString("Demo_MicroFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مربعات النص.
        /// </summary>
        public static string Demo_Modals {
            get {
                return ResourceManager.GetString("Demo_Modals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم الاختيار.
        /// </summary>
        public static string Demo_NotCheck {
            get {
                return ResourceManager.GetString("Demo_NotCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختبار.
        /// </summary>
        public static string Demo_Option {
            get {
                return ResourceManager.GetString("Demo_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختيار واحد.
        /// </summary>
        public static string Demo_OptionOne {
            get {
                return ResourceManager.GetString("Demo_OptionOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختيار اثنين.
        /// </summary>
        public static string Demo_OptionTwo {
            get {
                return ResourceManager.GetString("Demo_OptionTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخصائص.
        /// </summary>
        public static string Demo_Properties {
            get {
                return ResourceManager.GetString("Demo_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا النص هو مثال لنص.
        /// </summary>
        public static string Demo_ShortText {
            get {
                return ResourceManager.GetString("Demo_ShortText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اظهار مربع الإنتظار.
        /// </summary>
        public static string Demo_ShowLoading {
            get {
                return ResourceManager.GetString("Demo_ShowLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اظهار مربع النص.
        /// </summary>
        public static string Demo_ShowModal {
            get {
                return ResourceManager.GetString("Demo_ShowModal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاحجام.
        /// </summary>
        public static string Demo_Sizes {
            get {
                return ResourceManager.GetString("Demo_Sizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خط صغير.
        /// </summary>
        public static string Demo_SmallFont {
            get {
                return ResourceManager.GetString("Demo_SmallFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان فرعي.
        /// </summary>
        public static string Demo_Subtitle {
            get {
                return ResourceManager.GetString("Demo_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نجاح.
        /// </summary>
        public static string Demo_Success {
            get {
                return ResourceManager.GetString("Demo_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اظهار مربع نص النجاح.
        /// </summary>
        public static string Demo_SuccessModal {
            get {
                return ResourceManager.GetString("Demo_SuccessModal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفعيل.
        /// </summary>
        public static string Demo_Switch {
            get {
                return ResourceManager.GetString("Demo_Switch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان.
        /// </summary>
        public static string Demo_Title {
            get {
                return ResourceManager.GetString("Demo_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنواين.
        /// </summary>
        public static string Demo_Titles {
            get {
                return ResourceManager.GetString("Demo_Titles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا النص هو مثال لنص يمكن أن يستبدل بنص اخر بديل بنفس المساحة.
        /// </summary>
        public static string Demo_TitleText {
            get {
                return ResourceManager.GetString("Demo_TitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخط.
        /// </summary>
        public static string Demo_Typography {
            get {
                return ResourceManager.GetString("Demo_Typography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحذير.
        /// </summary>
        public static string Demo_Warning {
            get {
                return ResourceManager.GetString("Demo_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الالكتروني.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرئيسية.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Dark.
        /// </summary>
        public static string IsDarkTheme {
            get {
                return ResourceManager.GetString("IsDarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اللغة.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موافق.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تنفيذ العملية بنجاح !.
        /// </summary>
        public static string OperationSuccess {
            get {
                return ResourceManager.GetString("OperationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مفتاح الخط.
        /// </summary>
        public static string PhoneCode {
            get {
                return ResourceManager.GetString("PhoneCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرجاء الانتظار ....
        /// </summary>
        public static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التعداد السكاني.
        /// </summary>
        public static string Population {
            get {
                return ResourceManager.GetString("Population", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعدادات.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التبويبات.
        /// </summary>
        public static string Tabs {
            get {
                return ResourceManager.GetString("Tabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأنماط.
        /// </summary>
        public static string Themes {
            get {
                return ResourceManager.GetString("Themes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرجاء ادخال البريد الالكتروني بطريقة صحيحة.
        /// </summary>
        public static string Validation_Email {
            get {
                return ResourceManager.GetString("Validation_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حقل {0} مطلوب..
        /// </summary>
        public static string Validation_Required {
            get {
                return ResourceManager.GetString("Validation_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نعم.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
